### ISSUE TITLE
Issues executing code in Section 15.12 (at least for a windows machine)

### ISSUE THREAD

**Issue by beanb2** [rafalab/dsbook-part-1#1]
I am using R 4.3.1 via Rstudio on a Microsoft Windows 11 Pro Operating System (Version: 10.0.22621 Build 22621).  Running the following code resulted in a series of pdf errors:

library("pdftools")
temp_file <- tempfile()
url <- paste0("https://web.archive.org/web/20150927033124/",
              "https://www.pnas.org/content/suppl/2015/09/16/",
              "1510159112.DCSupplemental/pnas.201510159SI.pdf")
download.file(url, temp_file)
txt <- pdf_text(temp_file)
file.remove(temp_file)

These errors included, but were not limited to:
PDF error (174491): Illegal character '>'
PDF error (174500): Illegal character <2f> in hex string

My problem was fixed (courtesy of https://stackoverflow.com/questions/53455431/r-script-pdf-error-illegal-character-in-hex-string-when-i-am-searching-for-k) by adding mode = "wb" to the download.file function. However, the tables contained blank lines in the character vector not anticipated in the book version of the code. This required a change in indices in multiple places. The following code achieves the match desired at the end of the section: 

temp_file <- tempfile()
url <- paste0("https://web.archive.org/web/20150927033124/",
              "https://www.pnas.org/content/suppl/2015/09/16/",
              "1510159112.DCSupplemental/pnas.201510159SI.pdf")

download.file(url, temp_file, mode = "wb")
txt <- pdf_text(temp_file)
file.remove(temp_file)

raw_data_research_funding_rates <- txt[2]

tab <- str_split(raw_data_research_funding_rates, "\n")
tab <- tab[[1]]

the_names_1 <- tab[3]
the_names_2 <- tab[5]

the_names_1
the_names_1 <- the_names_1 |>
  str_trim() |>
  str_replace_all(",\\s.", "") |>
  str_split("\\s{2,}", simplify = TRUE)
the_names_1 

the_names_2
the_names_2 <- the_names_2 |>
  str_trim() |>
  str_split("\\s+", simplify = TRUE)
the_names_2

tmp_names <- str_c(rep(the_names_1, each = 3), the_names_2[-1], sep = "_")
the_names <- c(the_names_2[1], tmp_names) |>
  str_to_lower() |>
  str_replace_all("\\s", "_")
the_names

new_research_funding_rates <- tab[8:16] |>
  str_trim() |>
  str_split("\\s{2,}", simplify = TRUE) |>
  data.frame() |>
  setNames(the_names) |>
  mutate_at(-1, parse_number)

new_research_funding_rates |> as_tibble()

identical(research_funding_rates, new_research_funding_rates)

**Comment by rafalab** [comment]
Thanks for pointing this out. 

Once you add the `mode = "wb"` options, you can simply change

```
 tab <- str_split(raw_data_research_funding_rates, "\n")
 ```
 
to

```
 tab <- str_split(raw_data_research_funding_rates, "\n+")
 ```

and the rest of the code should work. Microsoft Windows and macOS (which is based on Unix) use different conventions for line endings in text files and a result `raw_data_research_funding_rates` has more `\n` when using Windows. 

I will edit the book to make this all clear.
