### ISSUE TITLE
Broken Links 

### ISSUE THREAD

**Issue by aizawa82** [rafalab/dsbook-part-1#3]
at least these don't seem to work

1. http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/dataviz-in-practice.html
2. http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/data-table-wrangling.html
3. http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/text-analysis.html

and the links in the references do not work either

**Comment by rafalab** [comment]
This should be fixed now. 
For the last few weeks I have been updating the quarto files but not the web page. 
Thanks for letting me know!
