### ISSUE TITLE
WSJ figure

### ISSUE THREAD

**Issue by tci1** [rafalab/dsbook-part-1#6]
10.9 says "Earlier we used an example provided by a Wall Street Journal article..." I searched "wall street" ... it looks it wasn't introduced earlier.

**Comment by rafalab** [comment]
It's in the introduction to the Data Visualization part: https://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/intro-dataviz.html

I'll edit the text to make that clearer.
