### ISSUE TITLE
How to remove the lines at the corner

### ISSUE THREAD

**Issue by Firestar-Reimu** [rafalab/dsbook-part-1#9]
![image](https://github.com/rafalab/dsbook-part-1/assets/65082432/572db597-827c-44f2-bd0f-af63e1bb1927)

this is the pdf on https://leanpub.com/datasciencebook

every page look like this:

```
_|      |_
   page
_        _
 |      |
```

how to remove the lines at the corner?

**Comment by rafalab** [comment]
That comes from the latex style used to produce that particular PDF. You can compile the pdf version of the book with whatever style you prefer.

**Comment by Firestar-Reimu** [comment]
Where is the tex source file and how to compile it? I cannot find them.
